### PR TITLE
Use AsyncPipeline

### PR DESCRIPTION
**Pull request by dkurt**
Processing time (OS-3.ndpi):

Threads: 890 seconds (14m50s)
AsyncPipeline: 979 seconds (16m19s)

### CODE REVIEW

**Comment by Wovchena** [comment]
Can you share cmd line? If you ran with default number of `-nireq`, than this can be the case, executable_network sets it to a value equal to `nstreams` which isn't correct. It should be little higher. Or much higher if latency is out of concern, which is true for the demo. We have that trick with default values only for C++ for now:
https://github.com/openvinotoolkit/open_model_zoo/blob/fc32c1f421ed0952e71c112ad826399338a3dd09/demos/common/cpp/pipelines/src/async_pipeline.cpp#L63
For old version I have
`py ..\stardist_demo\python\stardist_demo.py -i C:\Users\vzlobin\Downloads\CMU-3.ndpi -m C:\Users\vzlobin\Downloads\d\public\stardist_he\FP16\stardist_he.xml`
`Done! 405.11984276771545`
and for this:
`py ..\stardist_demo\python\stardist_demo.py -i C:\Users\vzlobin\Downloads\CMU-3.ndpi -m C:\Users\vzlobin\Downloads\d\public\stardist_he\FP16\stardist_he.xml -nstreams 4 -nireq 8`
`finish 393.4605221748352`

`OS-3.ndpi` is too big for 16GB on my laptop :)

i7-7820hq, Windows

Just realized, if I remove result storing, `OS-3.ndpi` should fit into memory. I will try it later.

**Comment by dkurt** [comment]
@Wovchena, I just use default flags (auto number of streams and infer requests is 4). By the way, that would be nice to print such values in the log (like benchmark does). I'm going to update this PR with something intermediate (keeping just a single thread for NMS)

**Comment by Wovchena** [comment]
I still think it needs to be shown that `AsyncPipeline` is bad to agree with your intermediate solution (whatever it is :) ). At least it will reveal `AsyncPipeline`'s problems. It is important because we use it widely. And if there is no rush, you are at risk ending up writing just another solution which won't be used.
I still believe it's not a good idea to have another thread running pure python because of GIL.

To be honest there is a known problem with `AsyncPipeline`: python shouldn't use callbacks in IE, because of that GIL again. But since your way also includes that problem, they should kind of cancel out.

BTW, just to inform, `OS-3.ndpi` failed again with Predictions queue size of 80 :) I guess that's not about storing results in `detections`.

**Comment by dkurt** [comment]
@Wovchena, yeah, that's going to be solved (better to store predictions filtered by confidence threshold rather than raw output tensors).

**Comment by dkurt** [comment]
see more optimal https://github.com/dkurt/open_model_zoo/pull/3

**Pull request closed without merging**
